"""roost-pytest test-suite configuration.

This file is auto-generated. It registers the custom markers used by
generated tests so pytest doesn't warn ``PytestUnknownMarkWarning``.
Add your own fixtures/hooks below the marker block as you would in
any pytest project.
"""

from __future__ import annotations

import pytest


_GENERATED_MARKERS = {
    'generated': 'test was auto-generated by roost-pytest',
    'happy_path': 'exercises the primary success path',
    'edge_case': 'exercises an edge / boundary condition',
    'error_path': 'exercises an exception or failure path',
    'security': 'exercises a security-sensitive behaviour',
    'property': 'property / invariant test (often parametrised)',
    'regression': 'guards against a previously fixed bug',
}


def pytest_configure(config: pytest.Config) -> None:
    for name, description in _GENERATED_MARKERS.items():
        config.addinivalue_line("markers", f"{name}: {description}")
