# ROOST_METHOD_HASH=convert_a2a_task_to_event_40cb3ce258
# ROOST_METHOD_SIG_HASH=convert_a2a_task_to_event_124ed678ea

"""Tests for `src.google.adk.a2a.converters.event_converter.convert_a2a_task_to_event`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: src/google/adk/a2a/converters/event_converter.py:201-265
# Scenarios:
#   - [happy_path] happy_path_task_with_artifacts: Verifies conversion when the Task has artifacts with parts, producing a valid Event.
#   - [edge_case] minimal_event_no_message: Checks that a minimal Event is created when Task has no artifacts, status, or history.
#   - [error_path] error_on_none_task: Ensures ValueError is raised if a2a_task is None.
#   - [error_path] runtime_error_on_message_conversion_failure: Ensures RuntimeError is raised if message conversion fails internally.
#   - [property] invocation_context_branch_and_id_propagation: Checks that branch and invocation_id from InvocationContext are propagated to the Event.

import pytest
from unittest import mock

from google.adk.a2a.converters.event_converter import convert_a2a_task_to_event

# Minimal fakes for required types (since real ones are unavailable in the workspace)
def make_part(text=None):
    class FakeTextPart:
        def __init__(self, text):
            self.text = text
    return FakeTextPart(text)

class Artifact:
    def __init__(self, parts=None):
        self.parts = parts or []

class Task:
    def __init__(self, artifacts=None, status=None, history=None):
        self.artifacts = artifacts or []
        self.status = status
        self.history = history or []

class Message:
    def __init__(self, message_id="", role=None, parts=None):
        self.message_id = message_id
        self.role = role
        self.parts = parts or []

class Event:
    def __init__(self, invocation_id=None, author=None, branch=None, content=None):
        self.invocation_id = invocation_id
        self.author = author
        self.branch = branch
        self.content = content

class InvocationContext:
    def __init__(self, invocation_id=None, branch=None):
        self.invocation_id = invocation_id
        self.branch = branch

def fake_convert_a2a_message_to_event(message, author, invocation_context, part_converter=None):
    # Simulate conversion: just wrap the message's parts in Event.content
    class Content:
        def __init__(self, parts):
            self.parts = parts
    return Event(
        invocation_id=invocation_context.invocation_id if invocation_context else "iid",
        author=author or "a2a agent",
        branch=invocation_context.branch if invocation_context else None,
        content=Content(message.parts)
    )

@pytest.fixture(autouse=True)
def patch_types(monkeypatch):
    monkeypatch.setattr("a2a.types.Task", Task)
    monkeypatch.setattr("a2a.types.Artifact", Artifact)
    monkeypatch.setattr("a2a.types.Part", make_part)
    monkeypatch.setattr("a2a.types.TextPart", make_part)
    monkeypatch.setattr("a2a.types.Message", Message)
    monkeypatch.setattr("google.adk.a2a.converters.event_converter.Event", Event)
    monkeypatch.setattr("google.adk.a2a.converters.event_converter.InvocationContext", InvocationContext)

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_task_with_artifacts(monkeypatch):
    """Verifies conversion when the Task has artifacts with parts, producing a valid Event."""
    # Patch convert_a2a_message_to_event to our fake
    monkeypatch.setattr(
        "google.adk.a2a.converters.event_converter.convert_a2a_message_to_event",
        fake_convert_a2a_message_to_event
    )
    a2a_task = Task(artifacts=[Artifact(parts=[make_part(text='foo')])], status=None, history=None)
    result = convert_a2a_task_to_event(a2a_task)
    assert isinstance(result, Event)
    assert hasattr(result, "content")
    assert getattr(result.content.parts[0], 'text', None) == 'foo'

@pytest.mark.generated
@pytest.mark.edge_case
def test_minimal_event_no_message(monkeypatch):
    """Checks that a minimal Event is created when Task has no artifacts, status, or history."""
    # Patch convert_a2a_message_to_event to ensure it's not called
    monkeypatch.setattr(
        "google.adk.a2a.converters.event_converter.convert_a2a_message_to_event",
        lambda *a, **kw: pytest.fail("Should not be called")
    )
    a2a_task = Task(artifacts=[], status=None, history=[])
    result = convert_a2a_task_to_event(a2a_task)
    assert isinstance(result, Event)
    assert getattr(result, "content", None) is None

@pytest.mark.generated
@pytest.mark.error_path
def test_error_on_none_task():
    """Ensures ValueError is raised if a2a_task is None."""
    with pytest.raises(ValueError):
        convert_a2a_task_to_event(None)

@pytest.mark.generated
@pytest.mark.error_path
def test_runtime_error_on_message_conversion_failure(monkeypatch):
    """Ensures RuntimeError is raised if message conversion fails internally."""
    def part_converter(_):
        raise Exception('fail')
    # Patch convert_a2a_message_to_event to raise Exception
    def fail_convert(*a, **kw):
        raise Exception('fail')
    monkeypatch.setattr(
        "google.adk.a2a.converters.event_converter.convert_a2a_message_to_event",
        fail_convert
    )
    a2a_task = Task(artifacts=[Artifact(parts=[make_part(text='foo')])], status=None, history=None)
    with pytest.raises(RuntimeError):
        convert_a2a_task_to_event(a2a_task, part_converter=part_converter)

@pytest.mark.generated
@pytest.mark.property
def test_invocation_context_branch_and_id_propagation(monkeypatch):
    """Checks that branch and invocation_id from InvocationContext are propagated to the Event."""
    # Patch convert_a2a_message_to_event to our fake
    monkeypatch.setattr(
        "google.adk.a2a.converters.event_converter.convert_a2a_message_to_event",
        fake_convert_a2a_message_to_event
    )
    ctx = InvocationContext(invocation_id='123', branch='main')
    a2a_task = Task(artifacts=[], status=None, history=[])
    result = convert_a2a_task_to_event(a2a_task, invocation_context=ctx)
    assert result.invocation_id == '123'
    assert result.branch == 'main'
