# ROOST_METHOD_HASH=convert_a2a_task_to_event_40cb3ce258
# ROOST_METHOD_SIG_HASH=convert_a2a_task_to_event_124ed678ea

"""Tests for `src.google.adk.a2a.converters.event_converter.convert_a2a_task_to_event`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: src/google/adk/a2a/converters/event_converter.py:201-265
# Scenarios:
#   - [happy_path] happy_path_with_artifacts: Verify that the function correctly extracts the message from task artifacts when they are present.
#   - [happy_path] happy_path_with_status_message: Verify that the function correctly extracts the message from task status when artifacts are missing.
#   - [happy_path] happy_path_with_history: Verify that the function correctly extracts the message from task history when artifacts and status message are missing.
#   - [happy_path] happy_path_minimal_event: Verify that the function returns a minimal Event when no message source is available in the task.
#   - [edge_case] edge_case_with_invocation_context: Verify that the function correctly uses the provided invocation context for the resulting Event.
#   - [error_path] error_path_none_task: Verify that the function raises ValueError when the input task is None.
#   - [error_path] error_path_conversion_failure: Verify that the function raises RuntimeError when the underlying message conversion fails.

import pytest
from unittest.mock import MagicMock, patch, ANY
import uuid

from a2a.types import Message, Role, Task, Part as A2APart, TextPart
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events.event import Event
from google.adk.a2a.converters.event_converter import convert_a2a_task_to_event

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_with_artifacts():
    """Verify that the function correctly extracts the message from task artifacts when they are present."""
    a2a_task = MagicMock(spec=Task)
    # Use real Part and TextPart to avoid Pydantic validation errors in Message constructor
    mock_part = A2APart(root=TextPart(text="test artifact"))
    a2a_task.artifacts = [MagicMock(parts=[mock_part])]
    a2a_task.status = None
    a2a_task.history = []
    
    mock_event = MagicMock(spec=Event)
    
    with patch("google.adk.a2a.converters.event_converter.convert_a2a_message_to_event", return_value=mock_event) as mock_convert:
        result = convert_a2a_task_to_event(a2a_task)
        
        assert result == mock_event
        mock_convert.assert_called_once()
        call_args = mock_convert.call_args[0]
        passed_message = call_args[0]
        assert isinstance(passed_message, Message)
        assert passed_message.message_id == ""
        assert passed_message.role == Role.agent
        assert passed_message.parts == [mock_part]

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_with_status_message():
    """Verify that the function correctly extracts the message from task status when artifacts are missing."""
    a2a_task = MagicMock(spec=Task)
    a2a_task.artifacts = []
    mock_message = MagicMock(spec=Message)
    mock_message.parts = [MagicMock()]
    a2a_task.status = MagicMock(message=mock_message)
    a2a_task.history = []
    
    mock_event = MagicMock(spec=Event)
    
    with patch("google.adk.a2a.converters.event_converter.convert_a2a_message_to_event", return_value=mock_event) as mock_convert:
        result = convert_a2a_task_to_event(a2a_task)
        
        assert result == mock_event
        mock_convert.assert_called_once_with(mock_message, None, None, part_converter=ANY)

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_with_history():
    """Verify that the function correctly extracts the message from task history when artifacts and status message are missing."""
    a2a_task = MagicMock(spec=Task)
    a2a_task.artifacts = []
    a2a_task.status = None
    mock_message = MagicMock(spec=Message)
    a2a_task.history = [mock_message]
    
    mock_event = MagicMock(spec=Event)
    
    with patch("google.adk.a2a.converters.event_converter.convert_a2a_message_to_event", return_value=mock_event) as mock_convert:
        result = convert_a2a_task_to_event(a2a_task)
        
        assert result == mock_event
        mock_convert.assert_called_once_with(mock_message, None, None, part_converter=ANY)

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_minimal_event():
    """Verify that the function returns a minimal Event when no message source is available in the task."""
    a2a_task = MagicMock(spec=Task)
    a2a_task.artifacts = []
    a2a_task.status = None
    a2a_task.history = []
    
    fixed_uuid = "12345678-1234-5678-1234-567812345678"
    with patch("uuid.uuid4", return_value=uuid.UUID(fixed_uuid)):
        result = convert_a2a_task_to_event(a2a_task)
        
        assert isinstance(result, Event)
        assert result.author == "a2a agent"
        assert result.invocation_id == fixed_uuid
        assert result.branch is None

@pytest.mark.generated
@pytest.mark.edge_case
def test_edge_case_with_invocation_context():
    """Verify that the function correctly uses the provided invocation context for the resulting Event."""
    a2a_task = MagicMock(spec=Task)
    a2a_task.artifacts = []
    a2a_task.status = None
    a2a_task.history = []
    
    invocation_context = MagicMock(spec=InvocationContext)
    invocation_context.invocation_id = 'test-id'
    invocation_context.branch = 'test-branch'
    
    result = convert_a2a_task_to_event(a2a_task, invocation_context=invocation_context)
    
    assert isinstance(result, Event)
    assert result.invocation_id == 'test-id'
    assert result.branch == 'test-branch'

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_none_task():
    """Verify that the function raises ValueError when the input task is None."""
    with pytest.raises(ValueError, match="A2A task cannot be None"):
        convert_a2a_task_to_event(None)

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_conversion_failure():
    """Verify that the function raises RuntimeError when the underlying message conversion fails."""
    a2a_task = MagicMock(spec=Task)
    a2a_task.artifacts = []
    a2a_task.status = None
    a2a_task.history = [MagicMock(spec=Message)]
    
    with patch("google.adk.a2a.converters.event_converter.convert_a2a_message_to_event", side_effect=Exception("fail")):
        with pytest.raises(RuntimeError, match="Failed to convert task message: fail"):
            convert_a2a_task_to_event(a2a_task)
