# ROOST_METHOD_HASH=convert_a2a_task_to_event_40cb3ce258
# ROOST_METHOD_SIG_HASH=convert_a2a_task_to_event_124ed678ea

"""Tests for `src.google.adk.a2a.converters.event_converter.convert_a2a_task_to_event`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: src/google/adk/a2a/converters/event_converter.py:201-265
# Scenarios:
#   - [happy_path] happy_path_artifacts: Verifies that when a task has artifacts, the last artifact's parts are used to create a message for conversion.
#   - [happy_path] happy_path_status_message: Verifies that when a task has no artifacts but has a status message, that message is used for conversion.
#   - [happy_path] happy_path_history: Verifies that when a task has no artifacts or status message but has history, the last message in history is used.
#   - [edge_case] edge_case_no_content: Verifies that a minimal Event is returned when no message content is found in the task.
#   - [happy_path] with_invocation_context: Verifies that invocation_id and branch are correctly propagated from the InvocationContext.
#   - [error_path] error_none_task: Verifies that passing None as a2a_task raises a ValueError.
#   - [error_path] error_conversion_failure: Verifies that a RuntimeError is raised if the underlying message conversion fails.

import pytest
from unittest.mock import MagicMock, patch
from google.adk.a2a.converters.event_converter import convert_a2a_task_to_event

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_artifacts():
    """Verifies that when a task has artifacts, the last artifact's parts are used to create a message for conversion."""
    mock_task = MagicMock()
    mock_task.artifacts = [MagicMock(parts=['part1', 'part2'])]
    mock_task.status = None
    mock_task.history = []
    
    mock_event = MagicMock()
    
    with patch('google.adk.a2a.converters.event_converter.Message') as mock_message_cls, \
         patch('google.adk.a2a.converters.event_converter.Role') as mock_role_cls, \
         patch('google.adk.a2a.converters.event_converter.convert_a2a_message_to_event') as mock_convert:
        
        mock_convert.return_value = mock_event
        mock_message_instance = MagicMock()
        mock_message_cls.return_value = mock_message_instance
        
        result = convert_a2a_task_to_event(mock_task)
        
        mock_message_cls.assert_called_once_with(
            message_id="", role=mock_role_cls.agent, parts=['part1', 'part2']
        )
        mock_convert.assert_called_once()
        args, kwargs = mock_convert.call_args
        assert args[0] == mock_message_instance
        assert result == mock_event

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_status_message():
    """Verifies that when a task has no artifacts but has a status message, that message is used for conversion."""
    mock_task = MagicMock()
    mock_task.artifacts = []
    mock_task.status.message.parts = ['status_part']
    mock_task.status.message.role = 'agent'
    mock_task.history = []
    
    mock_event = MagicMock()
    
    with patch('google.adk.a2a.converters.event_converter.convert_a2a_message_to_event') as mock_convert:
        mock_convert.return_value = mock_event
        
        result = convert_a2a_task_to_event(mock_task)
        
        mock_convert.assert_called_once()
        args, kwargs = mock_convert.call_args
        assert args[0] == mock_task.status.message
        assert result == mock_event

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_history():
    """Verifies that when a task has no artifacts or status message but has history, the last message in history is used."""
    mock_task = MagicMock()
    mock_task.artifacts = []
    mock_task.status = None
    mock_task.history = [MagicMock(parts=['hist1']), MagicMock(parts=['hist2'])]
    
    mock_event = MagicMock()
    
    with patch('google.adk.a2a.converters.event_converter.convert_a2a_message_to_event') as mock_convert:
        mock_convert.return_value = mock_event
        
        result = convert_a2a_task_to_event(mock_task)
        
        mock_convert.assert_called_once()
        args, kwargs = mock_convert.call_args
        assert args[0] == mock_task.history[-1]
        assert result == mock_event

@pytest.mark.generated
@pytest.mark.edge_case
def test_edge_case_no_content():
    """Verifies that a minimal Event is returned when no message content is found in the task."""
    mock_task = MagicMock()
    mock_task.artifacts = []
    mock_task.status = None
    mock_task.history = []
    
    with patch('google.adk.a2a.converters.event_converter.Event') as mock_event_cls, \
         patch('google.adk.a2a.converters.event_converter.uuid.uuid4') as mock_uuid:
        
        mock_uuid.return_value = 'generated-id'
        mock_event_instance = MagicMock()
        mock_event_cls.return_value = mock_event_instance
        
        result = convert_a2a_task_to_event(mock_task)
        
        mock_event_cls.assert_called_once_with(
            invocation_id='generated-id',
            author='a2a agent',
            branch=None
        )
        assert result == mock_event_instance

@pytest.mark.generated
@pytest.mark.happy_path
def test_with_invocation_context():
    """Verifies that invocation_id and branch are correctly propagated from the InvocationContext."""
    mock_task = MagicMock()
    mock_task.artifacts = []
    mock_task.status = None
    mock_task.history = []
    
    mock_context = MagicMock()
    mock_context.invocation_id = 'ctx-id'
    mock_context.branch = 'ctx-branch'
    
    with patch('google.adk.a2a.converters.event_converter.Event') as mock_event_cls:
        mock_event_instance = MagicMock()
        mock_event_cls.return_value = mock_event_instance
        
        result = convert_a2a_task_to_event(mock_task, invocation_context=mock_context)
        
        mock_event_cls.assert_called_once_with(
            invocation_id='ctx-id',
            author='a2a agent',
            branch='ctx-branch'
        )
        assert result == mock_event_instance

@pytest.mark.generated
@pytest.mark.error_path
def test_error_none_task():
    """Verifies that passing None as a2a_task raises a ValueError."""
    with pytest.raises(ValueError, match="A2A task cannot be None"):
        convert_a2a_task_to_event(None)

@pytest.mark.generated
@pytest.mark.error_path
def test_error_conversion_failure():
    """Verifies that a RuntimeError is raised if the underlying message conversion fails."""
    mock_task = MagicMock()
    mock_task.artifacts = [MagicMock(parts=['p1'])]
    mock_task.status = None
    mock_task.history = []
    
    with patch('google.adk.a2a.converters.event_converter.Message'), \
         patch('google.adk.a2a.converters.event_converter.Role'), \
         patch('google.adk.a2a.converters.event_converter.convert_a2a_message_to_event', side_effect=Exception('inner error')):
        with pytest.raises(RuntimeError, match="Failed to convert task message: inner error"):
            convert_a2a_task_to_event(mock_task)
